baseURL = 'https://mattanderson.xyz/'
languageCode = 'en-us'
title = 'Matt Anderson'
theme = 'papermod'

[markup.goldmark.renderer]
  unsafe = true

[params]
  [params.profileMode]
    enabled = true
    title = "Matt Anderson"
    subtitle = """Senior Software Engineer

7 years building high-scale backend systems at Capital One & E-TRADE"""
    imageUrl = "profile.jpg"
    imageTitle = "Matt Anderson"
    imageWidth = 150
    imageHeight = 150

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sgmaniakk"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/matt-anderson-dev/"

  [[params.socialIcons]]
    name = "cv"
    url = "/resume.pdf"

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 10
