baseURL = 'https://mattanderson.xyz/'
languageCode = 'en-us'
title = 'Matt Anderson'
theme = 'papermod'

[params]
  [params.profileMode]
    enabled = true
    title = "Matt Anderson"
    subtitle = "Software Engineer"
    imageUrl = "profile.jpg"
    imageTitle = "Matt Anderson"
    imageWidth = 150
    imageHeight = 150
